import { AppComponent } from "./src/app.component";
import { Home } from "./src/app/features/home/home.component";
import { ProductCard } from "./src/app/shared/components/product-card.component"
import { HomeBrowse } from "./src/app/features/shoppingList/browse/home-browse.component"
import { NavbarComponent } from "./src/app/core/components/navbar/navbar.component"
import { SearchboxComponent } from "./src/app/core/components/searchbox/searchbox.component"
import { ListDataCardComponent } from "./src/app/shared/components/list-data-card.component"
import { QuantityProducts } from "./src/app/shared/components/quantity-products.component";
import { ShoppingList } from "./src/app/shared/models/shopping-list.model";